name: AcousticChat-IronForge
main: AcousticChat
version: 2.0
api-version: 1.17
loadbefore:
  - VentureChat
commands:
  ac:
    description: AcousticChat commands
    usage: /ac reload or /ac noise <number between 0 and 1> <text>
    
